Repository uber/kraken, pull requests merged in 2024-09, with the labels that each got.

#363 Fixed Broken Unit tests in Kraken
  lib/backend/registrybackend/security/security.go
  utils/httputil/httputil.go
Labels: bug

#361 Repository upkeep
  .github/workflows/build-and-test.yaml
Labels: enhancement

#353 Fix typo in CONFIGURATION.md
  docs/CONFIGURATION.md
Labels: Documentation

#364 Adding CGO flags to supress warnings and fix build failures
  .github/workflows/build-and-test.yaml
Labels: bug

#365 Added the init() method to the shadow backend and SQL backend code
  lib/backend/shadowbackend/client.go
  lib/backend/sqlbackend/client.go
Labels: bug
